language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t michal-agc/docker-react -f Dockerfile.dev .

script: 
    - docker run -e CI=true michal-agc/docker-react npm run test

    